### ISSUE TITLE
-e option fails if no arguments are provided

### ISSUE THREAD

**Issue by lambdamusic** [lambdamusic/Ontospy#33]
```
[michele.pasin]@Tartaruga:~>ontospy -e
OntoSpy v1.8.6
------------
You passed the arguments:
Traceback (most recent call last):
  File "/usr/local/bin/ontospy", line 11, in <module>
    sys.exit(main_cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ontospy/main.py", line 172, in main_cli
    g = Ontospy(sparql_endpoint=sources[0], verbose=verbose)
IndexError: tuple index out of range
```

**Comment by lambdamusic** [comment]
Fix v 1.8.8
