### ISSUE TITLE
Error with verbose option

### ISSUE THREAD

**Issue by lambdamusic** [lambdamusic/Ontospy#49]
```
ontospy scan https://scigraph.springernature.com/things/articles/628f2bf55fe35e5b7eb0ef066f4b2c8a
Parsing https://scigraph.springernature.com/things/articles/628f2bf55fe35e5b7eb0ef066f4b2c8a...
Traceback (most recent call last):
  File "/usr/local/bin/ontospy", line 11, in <module>
    sys.exit(main_cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ontospy/cli.py", line 124, in scan
    action_analyze(sources, endpoint)
  File "/usr/local/lib/python2.7/site-packages/ontospy/core/actions.py", line 81, in action_analyze
    g = Ontospy(uri_or_path=sources, verbose=verbose)
NameError: global name 'verbose' is not defined
```

**Comment by lambdamusic** [comment]
fixed
